@startuml
skinparam sequenceMessageAlign right
activate Client
Client -> Server : send request
activate Server
Server -> "User defined method" : handle request
activate "User defined method"
"User defined method" -> Server: set response
deactivate "User defined method"
Server -> Client : send response
deactivate Server
@enduml